### ISSUE TITLE
error appear when using list of subdomains

### ISSUE THREAD

**Issue by infosec-MA** [bp0lr/dmut#5]
hi,
first thanks for this awesome tool, 

here's the problem, when i try using the tool with a list of subdomains 
`cat all.list| dmut -d ~/go/src/github.com/bp0lr/dmut/words.txt -w 30 -s ~/Tools/recon/massdns/lists/resolvers.txt  -o all.list-dmut` 

### Note: the same all.list(is a txt file contiene subdomains ) work fine in altdns

this error showup:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7ff705]

goroutine 72 [running]:
main.generateTable(0xc0001f28f8, 0x3, 0xc0001f5000, 0xfd, 0xfd, 0x1f4, 0x3, 0x19, 0xc001fda000, 0xace, ...)
	/home/simo/go/src/github.com/bp0lr/dmut/main.go:345 +0x1f5
main.main.func1(0xc000032120, 0xc00000ec20, 0xc0002da5b0, 0xc0002da5a0)
	/home/simo/go/src/github.com/bp0lr/dmut/main.go:223 +0xd2
created by main.main
	/home/simo/go/src/github.com/bp0lr/dmut/main.go:221 +0xf35
```

Go version: go1.14 linux/amd64

**Comment by bp0lr** [comment]
Hi!,

the crash is on line 345
`domParse, _:=tld.Parse(domain)`

this happens when dmut split the domain to generate the sld, tld and trd.
One of your subdomains returns an error on the Parse and that generates the nil pointer dereference.

should be fixed now.
update dmut and make your test.
`go get -u -v github.com/bp0lr/dmut`

Please run the same command but add the flag -v and | grep "parsing".
Would be great if you can tell me which domain was the problem.

`cat all.list| dmut -d ~/go/src/github.com/bp0lr/dmut/words.txt -w 30 -s ~/Tools/recon/massdns/lists/resolvers.txt -o all.list-dmut -v | grep "parsing"`

thank you!

**Comment by infosec-MA** [comment]
the result of the command `cat all.list| dmut -d ~/go/src/github.com/bp0lr/dmut/words.txt -w 30 -s ~/Tools/recon/massdns/lists/resolvers.txt -o all.list-dmut -v | grep "parsing"` come up with 
[-] Error parsing url: com

that's a malformed subdomain, it's  contain the tld only, but altdns handle it ok
thank you

**Comment by bp0lr** [comment]
Great!
now thank to you, dmut can handle that error too!
