### ISSUE TITLE
Killed 

### ISSUE THREAD

**Issue by MR-pentestGuy** [bp0lr/dmut#6]
hey i have been using this commad 
 cat makers/alives2 | dmut -d ~/wordlist/bestdns.txt -w 100 --dns-timeout 300 --dns-retries 5 --dns-errorLimit 25 -s ~/.dmut/resolvers.txt --show-stats -o results.txt

it runs for some time doesn't gives ant output and after a short while it says "killed"

**Comment by MR-pentestGuy** [comment]
cat makers/alives2 | dmut -d ~/wordlist/bestdns.txt -w 500 --dns-timeout 300 --dns-retries 5 --dns-errorLimit 25 -s ~/.dmut/resolvers.txt --show-stats -o results.txt
[+] Workers amount should be between 1 and 150.
[+] The number of workers was set to 25.
Killed

no subdomains in results.txt

**Comment by bp0lr** [comment]
Hi @MR-pentestGuy,

this happens because alives2 should be generating a really large domain list.
the permutation list is generated in memory, so a big domain finishes eaten all your ram and the program dies.

I found this problem during testing, for a 1GB vps, something around 3000 domains * 250 permutations * 25 possible permutations =25m combinations. That insane for a small machine (more than 8 hours of work using 100 workers).
That why I didn't change the workflow to use a static file on the disk as altdns does.
 
Anyway, I'm no one to tell you how much you can make dmut work, so I will think about this and find a solution to solve this problem.

thank you for the report!
